# Generated by Django 5.1.4 on 2024-12-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loginuser_is_active_role_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
